-- Migration: revoke direct/client EXECUTE from the trigger-only function handle_new_user().
--
-- Context / problem
-- -----------------
-- `memareh.handle_new_user()` is a PostgreSQL TRIGGER function (RETURNS trigger,
-- SECURITY DEFINER, owner = postgres, search_path = ''). It is invoked exclusively by
-- the live trigger `on_auth_user_created` (AFTER INSERT ON auth.users FOR EACH ROW),
-- which creates the initial `memareh.profiles` row (id + display_name) when a new
-- Supabase auth user is created.
--
-- Repository audit (TASK 50) confirmed:
--   * no browser/server-action/API route/.rpc("handle_new_user") caller exists
--   * no script or migration invokes it directly
--   * signup/profile creation relies on the TRIGGER, not on a direct RPC
--   * PostgreSQL does NOT require the session role to hold EXECUTE on a trigger
--     function for the trigger to fire — the trigger runs under the function's own
--     SECURITY DEFINER/owner (postgres) context.
--
-- The function currently carries the inherited public default EXECUTE grant, so PUBLIC /
-- anon / authenticated / service_role all hold EXECUTE on a SECURITY DEFINER postgres-
-- owned function. That is unnecessary attack surface.
--
-- Fix
-- ---
-- Remove direct EXECUTE from runtime/client roles. The TRIGGER (`on_auth_user_created`)
-- is NOT touched, so trigger-driven profile creation continues to work normally. postgres
-- (owner) keeps EXECUTE intrinsically — no explicit owner grant required.
--
-- Scope guardrails (deliberately does NOT):
--   * NOT invoke the function.
--   * NOT CREATE OR REPLACE / DROP the function.
--   * NOT DROP / CREATE / ALTER the trigger.
--   * NOT alter auth.users or memareh.profiles.
--   * NOT touch sync_display_name_from_auth() / its trigger on_auth_user_updated.
--   * NOT change RLS or any other function/table grant.
--   * NOT include any secret literal.
--
-- Idempotency: REVOKE of an already-absent privilege is a no-op; safe to re-run and on a
-- fresh DB reset.

REVOKE EXECUTE
ON FUNCTION memareh.handle_new_user()
FROM PUBLIC, anon, authenticated, service_role;

-- ============================================================================
-- READ-ONLY VERIFICATION (run separately in Supabase SQL Editor; NOT executed by
-- this migration). Confirms the ACL is reduced and the trigger still fires.
-- ============================================================================
--
-- SELECT
--     has_function_privilege('public',        p.oid, 'EXECUTE') AS public_execute,
--     has_function_privilege('anon',          p.oid, 'EXECUTE') AS anon_execute,
--     has_function_privilege('authenticated', p.oid, 'EXECUTE') AS authenticated_execute,
--     has_function_privilege('service_role',  p.oid, 'EXECUTE') AS service_role_execute,
--     has_function_privilege('postgres',      p.oid, 'EXECUTE') AS postgres_execute
-- FROM pg_proc p
-- JOIN pg_namespace n ON n.oid = p.pronamespace
-- WHERE n.nspname = 'memareh' AND p.proname = 'handle_new_user';
--
-- -- Trigger intact (definition must remain unchanged):
-- SELECT tgname, pg_get_triggerdef(oid) AS def
-- FROM pg_trigger WHERE tgname = 'on_auth_user_created' AND NOT tgisinternal;
